window.MENU_DATA = {
  kr: [
    "김치찌개|한국인의 소울 푸드, 돼지고기와 김치의 얼큰한 조화",
    "된장찌개|구수한 국물과 두부, 애호박이 어우러진 집밥의 정석",
    "순두부찌개|부드러운 순두부와 매콤한 고추기름의 만남",
    "비빔밥|신선한 나물과 고추장, 참기름의 완벽한 밸런스",
    "돌솥비빔밥|따뜻한 돌솥에 눌어붙은 누룽지가 일품인 비빔밥",
    "삼겹살|지글지글 구워 먹는 국민 회식 메뉴",
    "목살 구이|기름기가 적고 담백한 돼지고기 구이",
    "항정살 구이|아삭아삭한 식감이 일품인 특수부위",
    "돼지갈비|달콤한 양념이 깊게 밴 부드러운 숯불구이",
    "소갈비찜|입안에서 살살 녹는 부드러운 소고기 찜 요리",
    "매운 갈비찜|스트레스 풀리는 매콤한 맛의 갈비찜",
    "제육볶음|매콤달콤한 양념에 볶아낸 돼지고기, 밥도둑",
    "오징어볶음|쫄깃한 오징어와 매콤한 양념의 조화",
    "쭈꾸미볶음|봄철 별미, 매콤하고 쫄깃한 식감",
    "낙지볶음|쓰러진 소도 일으킨다는 보양식, 화끈한 불맛",
    "불고기|달짝지근한 간장 양념의 소고기 요리",
    "뚝배기 불고기|국물 자박하게 끓여낸 1인용 불고기",
    "설렁탕|뽀얀 사골 국물에 소면과 밥을 말아먹는 든든한 한 끼",
    "곰탕|맑고 깊은 국물의 소고기 탕",
    "갈비탕|큼직한 갈빗대가 들어간 영양 만점 탕 요리",
    "육개장|얼큰한 국물과 찢은 소고기, 대파의 시원함",
    "삼계탕|여름철 몸보신 대표 메뉴, 닭 한 마리가 통째로",
    "닭볶음탕|매콤한 국물에 감자와 닭고기가 어우러진 요리",
    "찜닭|간장 소스의 짭조름한 맛과 당면의 조화",
    "치킨 (후라이드)|바삭바삭한 튀김옷과 촉촉한 속살",
    "치킨 (양념)|달콤하고 매콤한 소스가 매력적인 치킨",
    "닭강정|식어도 맛있는 매콤달콤 순살 치킨",
    "떡볶이|국민 간식, 매콤달콤한 떡과 오뎅",
    "로제 떡볶이|부드러운 크림과 매콤한 소스의 트렌디하고 고소한 맛",
    "라볶이|라면 사리를 넣어 더욱 푸짐하게 즐기는 떡볶이",
    "순대|소금이나 쌈장에 찍어 먹는 쫄깃한 별미",
    "튀김 (모듬)|김말이, 오징어, 야채 등 바삭한 즐거움",
    "김밥|간편하지만 든든한 한 줄, 다양한 속재료",
    "참치마요 김밥|고소한 참치와 마요네즈의 찰떡궁합",
    "돈까스|바삭한 일식 스타일 혹은 소스 듬뿍 경양식 스타일",
    "치즈 돈까스|자르면 치즈가 흘러넘치는 고소한 돈까스",
    "냉면 (물)|살얼음 동동 띄운 시원한 육수와 쫄깃한 면발",
    "냉면 (비빔)|매콤한 양념장에 비벼 먹는 입맛 돋우는 별미",
    "칼국수|뜨끈한 국물과 직접 썬 면발의 정겨운 맛",
    "바지락 칼국수|시원한 조개 국물이 일품인 칼국수",
    "장칼국수|고추장을 풀어 얼큰하고 걸쭉한 강원도식 칼국수",
    "수제비|손으로 툭툭 떼어 넣은 쫄깃한 반죽과 시원한 국물",
    "잔치국수|멸치 육수에 소면을 말아 호로록 먹는 경사스런 맛",
    "비빔국수|새콤달콤 매콤한 양념에 비빈 입맛 도는 국수",
    "쫄면|탱글탱글한 면발과 아삭한 채소의 조화",
    "만두국|속이 꽉 찬 만두와 뜨끈한 국물",
    "떡만두국|떡과 만두를 한 번에 즐기는 명절 같은 한 끼",
    "부대찌개|햄, 소세지, 라면사리의 푸짐한 의정부 스타일 찌개",
    "감자탕|돼지 등뼈의 살을 발라먹는 재미와 얼큰한 국물",
    "뼈해장국|점심 메뉴로 인기 만점, 든든한 한 그릇",
    "순대국|돼지 부속과 순대가 들어간 구수한 국밥",
    "돼지국밥|부산의 소울 푸드, 진한 국물과 부드러운 수육",
    "콩나물국밥|시원하고 맑은 국물, 숙취 해소에 최고",
    "추어탕|몸보신에 좋은 미꾸라지 탕",
    "아구찜|매콤한 콩나물찜과 쫄깃한 아귀살",
    "해물찜|다양한 해산물을 매콤하게 쪄낸 요리",
    "간장게장|밥도둑 계의 레전드, 짭조름한 감칠맛",
    "양념게장|매콤달콤한 양념에 버무린 게장",
    "보쌈|부드럽게 삶은 돼지고기와 김치의 조화",
    "족발|콜라겐 가득한 쫄깃한 껍질과 살코기",
    "잡채|명절이나 잔치에 빠지지 않는 당면 요리",
    "파전|비 오는 날 생각나는 해물과 파의 조화",
    "김치전|새콤한 김치를 송송 썰어 부쳐낸 바삭한 맛",
    "녹두빈대떡|광장시장의 맛, 고소하고 두툼한 전",
    "육회|신선한 소고기의 고소함을 그대로 느낄 수 있는 메뉴",
    "육회비빔밥|신선한 육회를 듬뿍 얹은 비빔밥",
    "마라탕|좋아하는 재료를 넣어 얼큰하게 즐기는 중독적인 맛",
    "마라샹궈|매콤하고 알싸하게 볶아낸 중국식 볶음요리",
    "탕수육|바삭한 튀김과 새콤달콤 소스 (부먹 vs 찍먹)",
    "짜장면|남녀노소 누구나 좋아하는 달콤짭짤한 맛",
    "짬뽕|각종 해물과 얼큰한 국물의 조화",
    "볶음밥 (중식)|고슬고슬하게 볶아낸 불맛 나는 밥",
    "깐풍기|매콤새콤한 소스에 볶은 닭튀김 요리",
    "유린기|바삭한 닭튀김에 상큼한 간장 소스와 고추를 곁들인 요리",
    "고추잡채|꽃빵에 싸 먹는 매콤한 피망과 고기 볶음",
    "마파두부|매콤하고 부드러운 두부 요리, 밥에 비벼 먹으면 최고",
    "쌀국수|진한 고기 육수와 숙주의 아삭함",
    "월남쌈|신선한 채소와 고기를 라이스페이퍼에 싸 먹는 건강식",
    "분짜|새콤달콤한 느억맘 소스에 찍어 먹는 베트남 국수",
    "나시고랭|인도네시아 스타일의 짭짤하고 매콤한 볶음밥",
    "팟타이|태국식 볶음 쌀국수, 땅콩 가루의 고소함",
    "초밥 (모듬)|다양한 생선을 한 번에 즐기는 깔끔한 식사",
    "회덮밥|신선한 회와 채소를 초장에 비벼 먹는 밥",
    "물회|새콤달콤 시원한 육수에 회를 말아 먹는 여름 별미",
    "알탕|톡톡 터지는 알과 곤이가 들어간 얼큰한 탕",
    "대구탕|시원하고 맑은 국물의 생선탕",
    "동태찌개|얼큰하고 칼칼한 생선 찌개",
    "고등어 구이|겉바속촉, 밥 반찬으로 최고의 생선구이",
    "갈치 조림|매콤한 양념이 밴 부드러운 갈치살",
    "샌드위치|신선한 채소와 햄, 치즈로 가볍게",
    "토스트|버터 향 가득한 식빵에 계란과 잼",
    "샐러드 (닭가슴살)|다이어트와 건강을 위한 가벼운 한 끼",
    "포케|하와이안 스타일의 신선한 회 덮밥 샐러드",
    "그릭 요거트 볼|꾸덕한 요거트와 그래놀라, 과일의 조화",
    "베이글 & 크림치즈|쫄깃한 빵과 부드러운 치즈",
    "브런치 플레이트|스크램블 에그, 소세지, 빵으로 여유로운 식사",
    "파스타 (토마토)|상큼한 토마토 소스의 기본 파스타",
    "파스타 (크림)|고소하고 진한 크림 소스 파스타",
    "파스타 (오일)|깔끔하고 담백한 알리오 올리오",
    "리조또|부드러운 크림이나 토마토 소스로 맛을 낸 쌀 요리",
    "피자 (페퍼로니)|짭조름한 페퍼로니가 가득한 클래식 피자",
    "피자 (고르곤졸라)|꿀에 찍어 먹는 고소한 치즈 피자",
    "스테이크|육즙 가득한 소고기 칼질",
    "햄버거 (수제)|육즙 가득한 패티와 신선한 야채",
    "카레라이스|향긋한 카레 향과 밥의 조화",
    "닭한마리|시원한 국물에 닭과 칼국수를 즐기는 요리",
    "어묵탕|뜨끈한 국물에 다양한 어묵을 넣은 술안주",
    "곱창구이|고소한 곱이 가득 찬 소곱창 구이",
    "대창구이|기름진 맛이 일품인 소대창",
    "막창구이|쫄깃한 식감이 매력적인 구이",
    "양꼬치|숯불에 돌려가며 굽는 양고기 꼬치",
    "마라탕면|마라탕에 면을 추가해 든든하게 즐기는 요리",
    "우동|오동통한 면발과 시원한 국물",
    "냉모밀|여름철 시원하게 즐기는 메밀국수",
    "판모밀|쯔유 소스에 찍어 먹는 깔끔한 메밀국수",
    "샤브샤브|얇은 고기와 채소를 육수에 살짝 익혀 먹는 요리",
    "편백찜|편백나무 통에 고기와 채소를 쪄낸 담백한 요리"
  ],
  us: [
    "Cheeseburger|Juicy beef patty with cheddar cheese, lettuce, and tomato",
    "Double Bacon Cheeseburger|For the meat lovers, double patties and crispy bacon",
    "Mushroom Swiss Burger|Savory sautéed mushrooms and melted Swiss cheese",
    "Philly Cheesesteak|Thinly sliced ribeye steak with melted cheese on a hoagie roll",
    "Reuben Sandwich|Corned beef, Swiss cheese, sauerkraut, and Russian dressing on rye",
    "BLT Sandwich|Crispy bacon, fresh lettuce, and tomato. Simple and perfect",
    "Club Sandwich|Triple-decker sandwich with turkey, bacon, lettuce, and tomato",
    "Grilled Cheese|Melted gooey cheese between buttery toasted bread",
    "Tomato Soup & Grilled Cheese|The ultimate comfort food combo",
    "Hot Dog|Classic ballpark frank with mustard and relish",
    "Chili Dog|Hot dog topped with savory meat chili and cheese",
    "Corn Dog|Sausage on a stick coated in a thick layer of cornmeal batter",
    "Buffalo Wings|Deep-fried chicken wings tossed in spicy buffalo sauce",
    "BBQ Ribs|Tender pork ribs coated in smoky barbecue sauce",
    "Pulled Pork Sandwich|Slow-cooked shredded pork with BBQ sauce on a bun",
    "Brisket|Smoked beef brisket, tender and flavorful",
    "Fried Chicken|Southern style crispy golden fried chicken",
    "Chicken and Waffles|Sweet and savory combination with syrup",
    "Macaroni and Cheese|Creamy, cheesy pasta baked to perfection",
    "Meatloaf|Ground beef loaf mixed with spices, served with mashed potatoes",
    "Pot Roast|Slow-cooked beef roast with carrots and potatoes",
    "Steak Frites|Grilled steak served with french fries",
    "New York Strip Steak|A tender cut of beef, grilled to your liking",
    "Ribeye Steak|Rich, juicy, and full-flavored steak",
    "Filet Mignon|The most tender cut of beef, melt-in-your-mouth",
    "Surf and Turf|Steak and lobster/shrimp combination",
    "Clam Chowder|Creamy soup with clams, potatoes, and bacon (New England style)",
    "Lobster Roll|Fresh lobster meat in a buttered hot dog bun",
    "Crab Cakes|Pan-fried patties of crab meat and breadcrumbs",
    "Jambalaya|Creole rice dish with meat, vegetables, and seafood",
    "Gumbo|Hearty stew with strong flavors, meat, or shellfish",
    "Cobb Salad|Garden salad with tomato, bacon, chicken, egg, avocado, and cheese",
    "Caesar Salad|Romaine lettuce, croutons, parmesan cheese, and caesar dressing",
    "Waldorf Salad|Fruit and nut salad with celery and mayonnaise",
    "Pepperoni Pizza|American favorite thin or thick crust pizza",
    "Chicago Deep Dish Pizza|Thick crust pizza with layers of cheese and tomato sauce",
    "Hawaiian Pizza|Ham and pineapple topping (controversial but popular)",
    "Meat Lovers Pizza|Topped with pepperoni, sausage, bacon, and ham",
    "Bagel with Lox|Cream cheese and smoked salmon on a bagel",
    "Eggs Benedict|Poached eggs and canadian bacon on an English muffin with hollandaise",
    "Pancakes|Fluffy stack of pancakes with maple syrup",
    "French Toast|Bread soaked in eggs and milk, fried and topped with syrup",
    "Breakfast Burrito|Tortilla filled with eggs, cheese, potatoes, and meat",
    "California Roll|Sushi roll with crab, avocado, and cucumber",
    "Spicy Tuna Roll|Sushi roll with spicy tuna mix",
    "Poke Bowl|Hawaiian raw fish salad with rice and toppings",
    "Chipotle Burrito|Mission-style burrito with rice, beans, and meat",
    "Nachos|Tortilla chips topped with cheese, jalapeños, and salsa",
    "Tacos (Hard Shell)|Ground beef, lettuce, and cheese in a crispy shell",
    "Fajitas|Sizzling grilled meat and vegetables served with tortillas",
    "Quesadilla|Tortilla filled with cheese and meat, grilled until melted",
    "Spaghetti and Meatballs|Italian-American classic pasta dish",
    "Chicken Parmesan|Breaded chicken breast topped with marinara and cheese",
    "Fettuccine Alfredo|Pasta in a rich, creamy parmesan cheese sauce",
    "Lasagna|Layers of pasta, meat sauce, and cheese baked together",
    "Baked Ziti|Pasta baked with marinara sauce and cheese",
    "Turkey Dinner|Roast turkey with stuffing and cranberry sauce",
    "Chicken Pot Pie|Savory pie filled with chicken and vegetables",
    "Beef Stew|Hearty stew with chunks of beef and vegetables",
    "Sloppy Joes|Ground beef in a sweet and tangy tomato sauce on a bun",
    "Tuna Casserole|Baked pasta dish with tuna and creamy mushroom soup",
    "Deviled Eggs|Hard-boiled eggs filled with a creamy yolk mixture",
    "Potato Salad|Boiled potatoes in a mayonnaise-based dressing",
    "Coleslaw|Shredded cabbage salad with a creamy dressing",
    "Onion Rings|Battered and deep-fried onion rings",
    "Mozzarella Sticks|Breaded and fried cheese sticks with marinara dip",
    "Submarine Sandwich|Long roll filled with meats, cheese, and veggies",
    "Chicken Caesar Wrap|Caesar salad with chicken wrapped in a tortilla",
    "Smoothie Bowl|Thick fruit smoothie topped with granola and fruit",
    "Acai Bowl|Superfood berry bowl with toppings",
    "Avocado Toast|Toasted bread topped with mashed avocado and seasonings",
    "Beyond Burger|Plant-based burger that tastes like meat",
    "Shrimp Scampi|Shrimp cooked in garlic, butter, and white wine sauce",
    "Fish Tacos|Grilled or fried fish in corn tortillas with slaw",
    "Key Lime Pie|Sweet and tart dessert pie",
    "Apple Pie|Classic American dessert with vanilla ice cream",
    "Chicken Fried Steak|Breaded beef cutlet served with country gravy",
    "Biscuits and Gravy|Soft dough biscuits covered in pork sausage gravy",
    "Po' Boy|Traditional Louisiana sandwich with fried seafood",
    "Etouffee|Shellfish simmered in a roux-based sauce served over rice",
    "Cuban Sandwich|Ham, roasted pork, Swiss cheese, pickles, and mustard on Cuban bread",
    "Frito Pie|Chili, cheese, and onions served over corn chips",
    "Tater Tot Casserole|Casserole made with meat, chili, and crispy tater tots",
    "California Burrito|Burrito filled with carne asada and french fries",
    "Cioppino|Seafood stew originating from San Francisco"
  ],
  jp: [
    "Sushi (Nigiri)|Hand-pressed vinegared rice topped with fresh raw fish",
    "Sashimi|Freshly sliced raw fish served without rice",
    "Maki Sushi (Rolls)|Sushi rice and fillings wrapped in seaweed",
    "Chirashi Sushi|Bowl of sushi rice topped with scattered raw fish",
    "Tempura|Lightly battered and deep-fried seafood and vegetables",
    "Tonkatsu|Breaded and deep-fried pork cutlet",
    "Katsudon|Pork cutlet and egg cooked in dashi broth over rice",
    "Ramen (Shoyu)|Soy sauce based broth noodle soup",
    "Ramen (Miso)|Miso paste based broth noodle soup",
    "Ramen (Tonkotsu)|Rich pork bone broth noodle soup",
    "Ramen (Shio)|Salt based clear broth noodle soup",
    "Tsukemen|Dipping noodles served with a separate bowl of concentrated broth",
    "Udon (Kake)|Thick wheat noodles in a hot dashi broth",
    "Udon (Tempura)|Udon noodles topped with crispy tempura",
    "Udon (Curry)|Udon noodles in a thick curry broth",
    "Soba (Zaru)|Cold buckwheat noodles served with dipping sauce",
    "Soba (Kake)|Hot buckwheat noodles in broth",
    "Yakisoba|Stir-fried noodles with vegetables and meat",
    "Okonomiyaki|Savory pancake containing variety of ingredients (Osaka style)",
    "Monjayaki|Runnier version of Okonomiyaki (Tokyo style)",
    "Takoyaki|Ball-shaped snack containing diced octopus",
    "Yakitori|Grilled chicken skewers with tare sauce or salt",
    "Yakiniku|Japanese style BBQ, grilling meat at the table",
    "Shabu-Shabu|Hot pot dish with thinly sliced meat and vegetables",
    "Sukiyaki|Beef and vegetables cooked in a sweet soy sauce broth",
    "Nabe (Hot Pot)|Various ingredients cooked in a pot at the table",
    "Oden|Fish cakes, radish, and eggs stewed in a light dashi broth",
    "Gyudon (Beef Bowl)|Simmered beef and onions served over rice",
    "Oyakodon|Chicken and egg simmered together over rice",
    "Ten-don|Tempura served over a bowl of rice",
    "Unadon (Eel Bowl)|Grilled eel with sweet glaze over rice",
    "Curry Rice|Thick and sweet Japanese style curry with rice",
    "Katsu Curry|Curry rice topped with a pork cutlet",
    "Omurice|Omelette made with fried rice and topped with ketchup",
    "Hamburg Steak|Japanese style hamburger patty served with rice",
    "Karaage|Japanese style fried chicken",
    "Gyoza|Pan-fried dumplings with pork and vegetable filling",
    "Nikujaga|Meat and potato stew",
    "Saba Shioyaki|Grilled mackerel with salt",
    "Sanma Shioyaki|Grilled pacific saury",
    "Hokke|Grilled Okhotsk atka mackerel",
    "Tamagoyaki|Japanese rolled omelette",
    "Chawanmushi|Savory egg custard steamed in a cup",
    "Miso Soup|Traditional soup made with dashi and miso paste",
    "Onigiri (Plum)|Rice ball filled with pickled plum",
    "Onigiri (Salmon)|Rice ball filled with grilled salmon",
    "Onigiri (Tuna Mayo)|Rice ball filled with tuna and mayonnaise",
    "Inari Sushi|Sushi rice stuffed in seasoned deep-fried tofu pockets",
    "Natto|Fermented soybeans, often eaten with rice for breakfast",
    "Tofu (Hiyayakko)|Chilled tofu with toppings",
    "Agedashi Tofu|Deep-fried tofu in savory dashi broth",
    "Korokke (Croquette)|Deep-fried breaded mashed potato patties",
    "Menchi Katsu|Deep-fried breaded ground meat patty",
    "Ebi Fry|Breaded and deep-fried shrimp",
    "Kushikatsu|Deep-fried skewered meat and vegetables",
    "Champon|Noodle dish with pork, seafood and vegetables (Nagasaki style)",
    "Somen|Very thin white noodles served cold in summer",
    "Hiyashi Chuka|Chilled ramen noodles with various toppings",
    "Anpan|Sweet roll filled with red bean paste",
    "Melon Pan|Sweet bun with a cookie dough crust",
    "Dorayaki|Red bean pancake sandwich",
    "Taiyaki|Fish-shaped cake filled with red bean or custard",
    "Mochi|Rice cake",
    "Dango|Sweet rice dumplings on a skewer",
    "Matcha Ice Cream|Green tea flavored ice cream",
    "Kaiseki Ryori|Traditional multi-course Japanese dinner",
    "Teishoku|Set meal with main dish, rice, soup, and pickles",
    "Butadon|Pork bowl simmered in sweet soy sauce",
    "Tebasaki|Grilled chicken wings, famous in Nagoya",
    "Doteyaki|Beef tendons stewed in miso and mirin",
    "Jingisukan|Grilled lamb dish from Hokkaido",
    "Soup Curry|Spicy curry soup with vegetables and chicken"
  ],
  cn: [
    "Peking Duck|Crispy roasted duck served with pancakes",
    "Kung Pao Chicken|Spicy stir-fry with chicken, peanuts, and vegetables",
    "Mapo Tofu|Tofu in a spicy chili and bean-based sauce with minced meat",
    "Hot Pot|Simmering pot of soup with various ingredients to cook",
    "Dim Sum|Assortment of small steamed or fried savory dumplings",
    "Xiao Long Bao|Soup dumplings filled with pork and broth",
    "Dumplings (Jiaozi)|Boiled or pan-fried dumplings with meat filling",
    "Wonton Soup|Delicate dumplings in a clear broth",
    "Char Siu (BBQ Pork)|Sweet and savory roasted pork",
    "Sweet and Sour Pork|Deep-fried pork with pineapple and sweet vinegar sauce",
    "Chow Mein|Stir-fried noodles with vegetables and meat",
    "Fried Rice (Yangzhou)|Wok-fried rice with egg, shrimp, and ham",
    "Spring Rolls|Crispy fried rolls filled with vegetables",
    "Ma La Tang|Spicy numbing soup with ingredients of your choice",
    "Biang Biang Noodles|Thick hand-pulled noodles with chili oil",
    "Rou Jia Mo|Chinese hamburger, stewed pork in a bun",
    "Congee|Rice porridge, often served with century egg and pork",
    "Scallion Pancakes|Crispy and flaky pancakes with green onions",
    "Tomato and Egg Stir-fry|Classic home-style dish, simple and comforting",
    "Twice Cooked Pork|Sizzling pork belly stir-fried with leeks and chili",
    "Ants Climbing a Tree|Glass noodles stir-fried with minced meat",
    "Beggar's Chicken|Chicken stuffed and baked in clay",
    "Hainanese Chicken Rice|Poached chicken and seasoned rice (Wenchang origin)",
    "Dan Dan Noodles|Spicy noodles with minced pork and peanuts",
    "Lanzhou Beef Noodles|Clear soup with hand-pulled noodles and beef",
    "Zha Jiang Mian|Noodles with soybean paste and minced meat",
    "Shrimp with Vermicelli|Steamed shrimp with garlic and glass noodles",
    "Century Egg|Preserved duck egg with a unique flavor",
    "Stinky Tofu|Fermented tofu with a strong odor but delicious taste",
    "Braised Pork Belly (Hong Shao Rou)|Sweet and savory melt-in-your-mouth pork",
    "General Tso's Chicken|Sweet and spicy deep-fried chicken (Westernized favorite)",
    "Orange Chicken|Battered chicken in a sweet orange-flavored chili sauce",
    "Egg Foo Young|Omelette dish with vegetables and meat",
    "Moo Shu Pork|Stir-fried pork with wood ear mushrooms and eggs",
    "Fish Fragrant Eggplant|Eggplant stir-fried in a spicy garlic sauce (no fish)",
    "Sichuan Boiled Fish|Fish fillets poached in a spicy chili oil broth",
    "Cumin Lamb|Stir-fried lamb with cumin and spices",
    "Dongpo Pork|Pan-fried and red-cooked pork belly",
    "Lion's Head Meatballs|Large pork meatballs stewed with vegetables",
    "Buddha Jumps Over the Wall|Rich seafood and meat stew",
    "Mooncake|Dense pastry filled with red bean or lotus seed paste",
    "Tangyuan|Glutinous rice balls filled with sesame or peanut",
    "Soy Milk and You Tiao|Fried dough stick dipped in warm soy milk",
    "Tea Egg|Hard-boiled egg stewed in tea and spices",
    "Bubble Tea|Milk tea with tapioca pearls",
    "Malatang|Spicy hot pot soup street food",
    "Sichuan Wontons in Chili Oil|Spicy dumplings",
    "Shanghai Fried Noodles|Thick noodles fried with dark soy sauce",
    "Dry Pot (Mala Xiang Guo)|Stir-fried spicy pot without broth",
    "Claypot Rice|Rice cooked in a claypot with preserved meat",
    "Steamed Fish|Whole fish steamed with ginger and scallions",
    "Salt and Pepper Squid|Crispy squid tossed with spices",
    "Beef Chow Fun|Wide rice noodles stir-fried with beef",
    "Turnip Cake|Pan-fried radish cake, dim sum classic",
    "Egg Tart|Flaky pastry filled with egg custard"
  ],
  uk: [
    "Fish and Chips|Battered fish with thick fries", "Sunday Roast|Beef, potatoes, veg, and Yorkshire pudding", "Full English Breakfast|Eggs, bacon, sausage, beans, toast", "Bangers and Mash|Sausages with mashed potatoes and gravy", "Shepherd's Pie|Lamb mince topped with mashed potato", "Cottage Pie|Beef mince topped with mashed potato", "Toad in the Hole|Sausages baked in Yorkshire pudding batter", "Beef Wellington|Steak coated in pate and wrapped in puff pastry", "Cornish Pasty|Pastry filled with meat and veg", "Steak and Kidney Pie|Savory pie with beef and kidney", "Chicken Tikka Masala|Creamy curry, UK's national dish", "Ploughman's Lunch|Cheese, pickle, and bread platter", "Scotch Egg|Hard-boiled egg wrapped in sausage meat", "Black Pudding|Blood sausage, breakfast staple", "Haggis|Traditional Scottish savory pudding", "Welsh Rarebit|Cheese sauce on toast", "Eton Mess|Meringue, cream, and strawberries", "Scones with Clotted Cream|Tea time classic", "Victoria Sponge|Sponge cake with jam and cream", "Sticky Toffee Pudding|Sponge cake with toffee sauce", "Crumpets|Griddle cakes eaten with butter", "Jellied Eels|Traditional cockney dish", "Bubble and Squeak|Fried leftover vegetables", "Lancashire Hotpot|Lamb and potato stew", "Roast Chicken|Sunday classic with stuffing", "Pork Pie|Cold meat pie", "Kedgeree|Smoked haddock and rice dish", "Cucumber Sandwiches|Afternoon tea classic", "Trifle|Layered dessert with custard and fruit", "Spotted Dick|Suet pudding with dried fruit",
    "Bacon Sandwich|Bacon rashers between buttered white bread", "Beans on Toast|Baked beans served on buttered toast", "Steak and Ale Pie|Steak stewed in ale wrapped in pastry", "Cauliflower Cheese|Cauliflower baked in cheese sauce", "Gammon and Pineapple|Cured pork steak with grilled pineapple", "Kippers|Smoked herring, often for breakfast", "Beef and Guinness Stew|Rich stew made with stout beer", "Eccles Cake|Flaky pastry filled with currants", "Bakewell Tart|Shortcrust pastry with jam and almond filling", "Chelsea Bun|Currant bun with lemon peel and spices", "Yorkshire Pudding|Baked batter served with gravy", "Mince Pies|Christmas pastry filled with dried fruit", "Cullen Skink|Thick soup made of smoked haddock", "Stargazy Pie|Pie with fish heads protruding from crust", "Pie and Mash|Meat pie with mashed potatoes and liquor sauce"
  ],
  in: [
    "Butter Chicken|Creamy tomato curry", "Chicken Tikka Masala|Spiced curry with roasted chicken", "Biryani (Chicken)|Spiced rice with chicken", "Biryani (Mutton)|Spiced rice with goat meat", "Palak Paneer|Spinach curry with cottage cheese", "Chole Bhature|Spicy chickpeas with fried bread", "Masala Dosa|Crepe with potato filling", "Samosa|Fried pastry with savory filling", "Vada Pav|Spicy potato fritter in a bun", "Pav Bhaji|Vegetable mash with buttered bread", "Tandoori Chicken|Roasted chicken with yogurt and spices", "Rogann Josh|Aromatic lamb curry", "Dal Makhani|Creamy black lentil stew", "Aloo Gobi|Potato and cauliflower curry", "Naan (Garlic)|Oven-baked flatbread with garlic", "Pani Puri|Crispy hollow balls with spicy water", "Idli Sambar|Steamed rice cakes with lentil soup", "Uttapam|Thick pancake with vegetables", "Rasam|Spicy tamarind soup", "Gulab Jamun|Deep fried milk solids in syrup", "Jalebi|Sweet crispy spiral dessert", "Lassi|Yogurt drink", "Thali|Platter with various dishes", "Korma|Mild creamy curry", "Vindaloo|Spicy Goan curry",
    "Paneer Tikka|Grilled cottage cheese skewers", "Malai Kofta|Fried dumpling balls in creamy sauce", "Rajma Chawal|Red kidney bean curry with rice", "Bhindi Masala|Spiced okra stir-fry", "Kadai Paneer|Cottage cheese cooked in a wok with peppers", "Egg Curry|Boiled eggs in spicy tomato gravy", "Fish Curry|Fish cooked in coconut or tomato sauce", "Prawn Masala|Spicy prawn stir-fry", "Hyderabadi Biryani|Aromatic basmati rice with meat and spices", "Aloo Paratha|Flatbread stuffed with spiced potato", "Momos|Steamed dumplings with spicy chutney", "Bhel Puri|Puffed rice mixed with chutney and veggies", "Dahi Vada|Lentil balls soaked in yogurt", "Kulfi|Traditional Indian ice cream", "Rasgulla|Soft cheese balls in sugar syrup", "Dhokla|Steamed fermented batter cake", "Chicken 65|Spicy deep-fried chicken dish", "Mutton Korma|Tender mutton in rich creamy sauce", "Seekh Kebab|Minced meat grilled on skewers", "Baingan Bharta|Mashed roasted eggplant with spices"
  ],
  th: [
    "Pad Thai|Stir-fried noodles", "Tom Yum Goong|Spicy shrimp soup", "Green Curry|Coconut milk curry", "Som Tum|Spicy papaya salad", "Pad Kra Pao|Basil stir-fry with meat", "Khao Pad|Fried rice", "Massaman Curry|Rich peanut curry", "Panang Curry|Thick red curry", "Khao Soi|Curry noodle soup", "Mango Sticky Rice|Sweet dessert", "Tom Kha Gai|Chicken coconut soup", "Spring Rolls|Fried veggie rolls", "Satay|Grilled meat skewers", "Boat Noodles|Rich dark broth noodles", "Laab|Spicy minced meat salad", "Thai Omelette|Fluffy fried egg", "Fried Fish with Chili|Crispy fish with sauce", "Morning Glory Stir-fry|Vegetable side dish", "Thai Iced Tea|Sweet orange tea", "Roti|Sweet pancake",
    "Pad See Ew|Stir-fried wide rice noodles with soy sauce", "Gai Yang|Grilled Thai chicken", "Nam Tok Moo|Grilled pork salad with herbs", "Tod Mun Pla|Thai fish cakes", "Yum Woon Sen|Spicy glass noodle salad", "Pla Pao|Salt-crusted grilled fish", "Khao Man Gai|Hainanese style chicken rice", "Khao Kha Moo|Braised pork leg on rice", "Hor Mok|Steamed curry custard in banana leaf", "Kanom Jeen|Rice noodles with curry sauce", "Gaeng Som|Sour orange curry", "Sai Oua|Northern Thai sausage", "Moo Ping|Grilled pork skewers", "Cha Yen|Thai iced tea with milk", "Lod Chong|Pandan noodles in coconut milk", "Sang Kaya Fug Tong|Pumpkin custard", "Khanom Krok|Coconut rice pancakes", "Kuay Teow Neua|Beef noodle soup", "Goong Ob Woonsen|Baked shrimp with glass noodles", "Poo Pad Pong Karee|Stir-fried crab with yellow curry"
  ],
  au: [
    "Meat Pie|Pastry with meat filling", "Sausage Sizzle|Sausage on bread", "Chicken Parmigiana|Schnitzel with tomato and cheese", "Barramundi|Grilled local fish", "Pavlova|Meringue dessert with fruit", "Lamingtons|Sponge cake with chocolate and coconut", "Vegemite Toast|Salty spread on toast", "Burger with Beetroot|Aussie style burger", "Fish and Chips|Beachside classic", "Flat White|Coffee style", "Avocado Smash|Breakfast staple", "Tim Tam|Chocolate biscuit", "Anzac Biscuits|Oat cookies", "Kangaroo Steak|Lean game meat", "Lamb Roast|Sunday dinner favorite",
    "Chiko Roll|Deep-fried savory roll", "Dim Sim|Deep-fried snack", "Fairy Bread|Bread with butter and sprinkles", "Moreton Bay Bugs|Local lobster-like seafood", "Damper|Soda bread baked in coals", "Witchetty Grub|Indigenous bush tucker (adventurous!)", "Vanilla Slice|Custard square pastry", "Cherry Ripe|Cherry and coconut chocolate bar", "Iced VoVo|Biscuit with coconut and jam", "Pie Floater|Meat pie in pea soup", "Salt and Pepper Calamari|Pub classic appetizer", "Potato Scallops|Battered deep-fried potato slices", "Steak Sandwich|Steak, cheese, onion, and beetroot", "Continental Roll|Italian-influenced sandwich", "Seafood Platter|Assorted fresh seafood", "Emu Burger|Lean native meat burger", "Crocodile Meat|Game meat often smoked or grilled", "Macadamia Nut Cake|Cake made with native nuts", "Lemon, Lime and Bitters|Popular pub drink mix"
  ],
  ph: [
    "Adobo|Marinated meat stew", "Sinigang|Sour soup", "Lechon|Roast pig", "Sisig|Sizzling pork dish", "Pancit Canton|Stir-fried noodles", "Lumpia|Spring rolls", "Halo-Halo|Shaved ice dessert", "Kare-Kare|Peanut stew", "Chicken Inasal|Grilled chicken", "Tapsilog|Beef and egg rice", "Longganisa|Sweet sausage", "Balut|Fertilized duck egg", "Bicol Express|Spicy coconut pork", "Tinola|Chicken ginger soup", "Bibingka|Rice cake", "Champorado|Chocolate rice porridge",
    "Lechon Kawali|Crispy deep-fried pork belly", "Pancit Malabon|Stir-fried noodles with seafood topping", "Arroz Caldo|Chicken rice porridge", "Bulalo|Beef shank soup", "Dinuguan|Pork blood stew", "Pinakbet|Vegetable stew with shrimp paste", "Laing|Taro leaves in coconut milk", "Tocino|Sweet cured pork", "Kalamay|Sticky sweet rice cake", "Puto|Steamed rice cake", "Taho|Silken tofu with syrup and pearls", "Turon|Banana lumpia with caramel", "Buko Pandan|Coconut and pandan dessert", "Sinangag|Garlic fried rice", "Bangus (Milkfish)|National fish, often fried or grilled", "Kaldereta|Meat stew with liver spread", "Mechado|Beef stew with tomato sauce", "Ginataang Manok|Chicken in coconut milk", "Bistek Tagalog|Beef steak in soy sauce and onions"
  ],
  br: [
    "Feijoada|Black bean stew", "Churrasco|Brazilian BBQ", "Picanha|Top sirloin cap steak", "Moqueca|Fish stew", "Coxinha|Chicken croquette", "Pão de Queijo|Cheese bread", "Brigadeiro|Chocolate truffle", "Açaí|Berry bowl", "Pastel|Fried pastry", "Farofa|Toasted cassava flour side", "Vatapá|Shrimp and bread paste", "Acarajé|Black-eyed pea ball", "Guaraná|Popular soda", "Caipirinha|National cocktail",
    "Bauru|Roast beef sandwich with cheese", "Baião de Dois|Rice and beans with cheese and meat", "Bobó de Camarão|Shrimp in manioc cream", "Carne de Sol|Sun-dried salted beef", "Tacacá|Shrimp soup with jambu", "Coxinhas de Galinha|Chicken drumstick croquettes", "Kibe|Deep-fried beef croquette", "Empada|Small savory pie", "Esfirra|Middle-eastern inspired meat pie", "Mousse de Maracujá|Passion fruit mousse", "Quindim|Coconut egg custard", "Pudim|Condensed milk flan", "Tapioca Crepe|Crepe made from cassava starch", "Queijo Coalho|Grilled squeaky cheese", "Arroz Carreteiro|Rice with dried beef", "Salpicão|Chicken salad with mayo and potato sticks", "Cuscuz Branco|Coconut and tapioca pudding", "Canjica|Sweet corn pudding", "Romeu e Julieta|Guava paste and cheese"
  ],
  tw: [
    "Braised Pork Rice|Minced pork on rice", "Beef Noodle Soup|Rich beef broth noodles", "Bubble Tea|Tapioca milk tea", "Oyster Omelette|Egg with oysters", "Stinky Tofu|Fermented tofu", "Xiao Long Bao|Soup dumplings", "Pineapple Cake|Sweet pastry", "Fried Chicken Cutlet|Huge crispy chicken", "Scallion Pancake|Flaky savory pancake", "Dan Bing|Egg pancake roll", "Gua Bao|Pork belly bun", "Iron Egg|Stewed egg", "Three Cup Chicken|Basil chicken", "Mango Shaved Ice|Summer dessert", "Taro Ball Dessert|Chewy sweet balls",
    "Lu Rou Fan|Braised pork over rice", "Oyster Vermicelli|Thick noodle soup with oysters", "Coffin Bread|Deep-fried bread bowl with chowder", "Bawan|Meat dumpling in translucent wrapper", "Popcorn Chicken|Bite-sized fried chicken with basil", "Tube Rice Pudding|Sticky rice steamed in bamboo", "A-Gei|Meat-stuffed tofu skin", "Fish Ball Soup|Clear soup with bouncy fish balls", "Pepper Bun|Baked bun with pepper pork filling", "Peanut Ice Cream Roll|Ice cream wrapped in crepe with cilantro", "Douhua|Tofu pudding with toppings", "Soy Milk Chicken|Chicken marinated in fermented bean curd", "Turkey Rice|Shredded turkey over rice", "Milkfish Congee|Rice porridge with milkfish", "Sausage in Sausage|Taiwanese sausage wrapped in sticky rice sausage", "Sun Cake|Flaky pastry with maltose filling", "Hakka Stir-fry|Pork belly, squid, and dried tofu", "Bamboo Shoot Soup|Clear soup with seasonal bamboo shoots"
  ],
  ca: [
    "Poutine|Fries, cheese curds, gravy", "Maple Syrup Pancakes|Breakfast classic", "Butter Tarts|Sweet pastry", "Nanaimo Bars|No-bake dessert bar", "Montreal Smoked Meat|Cured beef sandwich", "Tourtière|Meat pie", "Peameal Bacon|Cornmeal rolled bacon", "Caesar Cocktail|Clamato drink", "BeaverTails|Fried dough pastry", "Split Pea Soup|Hearty soup", "Lobster Roll|Maritime favorite", "Saskatoon Berry Pie|Fruit pie", "Donair|Spiced meat wrap",
    "Bannock|Indigenous fried bread", "Timbits|Donut holes from Tim Hortons", "Montreal Bagel|Sweeter, denser bagel", "Kraft Dinner|Macaroni and cheese (national staple)", "Game Meat (Bison/Venison)|Lean wild meat dishes", "Jiggs Dinner|Salt beef and vegetable boil", "Rappie Pie|Potato and meat casserole", "Blueberry Grunt|Steamed blueberry pudding", "Garlic Fingers|Dough with garlic butter and cheese", "Pierogi Pizza|Pizza topped with potato dumplings", "Ginger Beef|Sweet and spicy deep-fried beef (Calgary style)", "London Fog|Earl Grey tea latte", "Coffee Crisp|Coffee flavored wafer bar", "Smarties|Chocolate covered candy", "Ketchup Chips|Tangy potato chips", "All-Dressed Chips|Mix of all chip flavors", "Ice Wine|Sweet dessert wine"
  ],
  sg: [
    "Chilli Crab|Spicy crab dish", "Hainanese Chicken Rice|Poached chicken rice", "Laksa|Spicy coconut noodles", "Char Kway Teow|Fried flat noodles", "Satay|Grilled skewers", "Bak Kut Teh|Pork rib tea soup", "Roti Prata|Flatbread with curry", "Hokkien Mee|Stir-fried prawn noodles", "Kaya Toast|Coconut jam toast", "Nasi Lemak|Coconut rice dish", "Fish Head Curry|Spicy curry", "Murtabak|Stuffed pancake", "Ice Kacang|Shaved ice dessert",
    "Carrot Cake (Chai Tow Kway)|Radish cake stir-fried with eggs", "Oyster Omelette|Egg omelette with oysters", "Wanton Mee|Egg noodles with dumplings", "Yong Tau Foo|Stuffed tofu and vegetables", "Rojak|Fruit and vegetable salad", "Mee Goreng|Spicy fried noodles", "Biryani|Spiced rice with meat", "Curry Puff|Pastry filled with curry potatoes", "Popiah|Fresh spring roll", "Cendol|Coconut milk dessert with green jelly", "Cheng Tng|Clear soup dessert", "Tau Huay|Soy bean pudding", "Mee Siam|Spicy rice vermicelli", "Mee Rebus|Noodles in sweet potato gravy", "Duck Rice|Braised duck over rice", "Kway Chap|Broad rice sheets in soy broth", "Chwee Kueh|Steamed rice cakes with radish", "Bak Chor Mee|Minced meat noodles", "Fishball Noodles|Noodles with bouncy fish balls"
  ],
  ae: [
    "Shawarma|Meat wrap", "Hummus|Chickpea dip", "Falafel|Fried chickpea balls", "Manakish|Levantine pizza", "Machboos|Spiced rice with meat", "Shish Tawook|Chicken skewers", "Knafeh|Sweet cheese pastry", "Fattoush|Bread salad", "Tabouleh|Parsley salad", "Luqaimat|Sweet dumplings", "Camel Burger|Exotic burger", "Harees|Wheat and meat porridge", "Karak Chai|Spiced tea",
    "Mandi|Rice and meat dish cooked in a pit", "Kabsa|Mixed rice dish", "Thareed|Stew served over flatbread", "Madrouba|Beaten rice and fish porridge", "Balaleet|Sweet vermicelli with saffron omelette", "Saloga|Rice dessert", "Ghouzi|Roasted lamb on rice", "Samak Mashwi|Grilled fish", "Baba Ganoush|Smoked eggplant dip", "Kousa Mahshi|Stuffed zucchini", "Warak Enab|Stuffed grape leaves", "Foul Medames|Stewed fava beans", "Shakshouka|Eggs poached in tomato sauce", "Umm Ali|Bread pudding dessert", "Basbousa|Semolina cake", "Mahalabiya|Milk pudding", "Jallab|Date and molasses drink", "Laban|Salty yogurt drink"
  ],
  de: [
    "Currywurst|Sausage with curry sauce", "Bratwurst|Fried sausage", "Schnitzel|Breaded cutlet", "Pretzel|Salty bread knot", "Sauerkraut|Fermented cabbage", "Potato Salad|Side dish", "Sauerbraten|Pot roast", "Spätzle|Egg noodles", "Rouladen|Rolled meat dish", "Black Forest Cake|Chocolate cherry cake", "Döner Kebab|Turkish-German sandwich", "Kartoffelpuffer|Potato pancakes", "Weisswurst|White sausage", "Apfelstrudel|Apple strudel",
    "Maultaschen|German ravioli", "Leberkäse|Meatloaf", "Königsberger Klopse|Meatballs in white sauce", "Eisbein|Pickled ham hock", "Schweinshaxe|Roasted pork knuckle", "Labskaus|Salted meat and potato dish", "Himmel und Erde|Mashed potatoes and apples", "Flammkuchen|Thin pizza-like tart", "Käsespätzle|Cheese noodles", "Obatzda|Cheese spread", "Stollen|Fruit bread", "Lebkuchen|Gingerbread", "Berliner|Filled doughnut", "Rote Grütze|Red fruit pudding", "Frankfurter Würstchen|Boiled sausage", "Thüringer Rostbratwurst|Grilled sausage", "Bienenstich|Bee sting cake", "Dampfnudel|Steamed dumpling", "Goulash|Meat stew", "Frikadellen|Pan-fried meatballs", "Matjes|Herring fillet"
  ]
};